language: c
compiler:
  - clang
  - gcc
script: sh configure ; make clean ; make sql
notifications:
  email:
    recipients:
      - greenboxal@gmail.com
      - roberto@forbrazil.com.br
      - carlos.lain@virtuati.com.br
      - marceloll@outlook.com
      - schrwaizer@hotmail.com
